export type Lang = 'RU' | 'KZ' | 'EN';

export const servicesText = {
  RU: { badge: 'Услуги Medsestra.kz', h1: 'Медицинский уход на дому', lead: 'Medsestra.kz организует выезд медсестры, уход на дому, поддержку семьи, корпоративный уход и wellness-направление. Мы отбираем медсестёр, проверяем документы и контролируем качество визита.', whatsapp: 'Написать в WhatsApp', prices: 'Посмотреть цены', all: 'Все направления', choose: 'Выберите услугу и город', chooseText: 'Эти страницы помогают пациенту быстро найти нужную услугу в своём районе и сразу перейти к записи.', zones: 'Алматы и область', zonesH: 'Зоны обслуживания', booking: 'Запись', bookingH: 'Нужна медсестра на дом?', bookingText: 'Напишите в WhatsApp или позвоните. Мы уточним услугу, район, время и подтвердим визит.' },
  KZ: { badge: 'Medsestra.kz қызметтері', h1: 'Үйдегі медициналық күтім', lead: 'Medsestra.kz үйге медбике шақыруды, үйдегі күтімді, отбасыға қолдауды, корпоративтік күтімді және wellness бағытын ұйымдастырады. Біз медбикелерді таңдаймыз, құжаттарын тексереміз және визит сапасын бақылаймыз.', whatsapp: 'WhatsApp арқылы жазу', prices: 'Бағаларды көру', all: 'Барлық бағыттар', choose: 'Қызмет пен қаланы таңдаңыз', chooseText: 'Бұл беттер пациентке өз ауданында қажетті қызметті тез тауып, жазылуға өтуге көмектеседі.', zones: 'Алматы және облыс', zonesH: 'Қызмет көрсету аймақтары', booking: 'Жазылу', bookingH: 'Үйге медбике керек пе?', bookingText: 'WhatsApp арқылы жазыңыз немесе қоңырау шалыңыз. Біз қызметті, ауданды, уақытты нақтылап, визитті растаймыз.' },
  EN: { badge: 'Medsestra.kz services', h1: 'Home medical care', lead: 'Medsestra.kz organizes nurse visits, home care, family support, corporate care and wellness services. We select nurses, check documents and control visit quality.', whatsapp: 'Message on WhatsApp', prices: 'View prices', all: 'All directions', choose: 'Choose a service and city', chooseText: 'These pages help patients quickly find the right service in their area and proceed to booking.', zones: 'Almaty and region', zonesH: 'Service areas', booking: 'Booking', bookingH: 'Need a nurse at home?', bookingText: 'Message us on WhatsApp or call. We will confirm the service, district, time and visit.' }
};

export const pricesText = {
  RU: { badge: 'Цены Medsestra.kz', h1: 'Стартовые тарифы', lead: 'Стоимость зависит от услуги, района, времени визита и срочности. Финальная цена подтверждается до визита.', cta: 'Записаться в WhatsApp', note: 'Цены указаны как ориентир. Если требуется дополнительное время, удалённая зона или срочный выезд, стоимость уточняется заранее.' },
  KZ: { badge: 'Medsestra.kz бағалары', h1: 'Бастапқы тарифтер', lead: 'Баға қызметке, ауданға, визит уақытына және жеделдікке байланысты. Соңғы баға визитке дейін расталады.', cta: 'WhatsApp арқылы жазылу', note: 'Бағалар бағдар ретінде көрсетілген. Қосымша уақыт, алыс аймақ немесе жедел шығу қажет болса, құны алдын ала нақтыланады.' },
  EN: { badge: 'Medsestra.kz prices', h1: 'Starting prices', lead: 'The price depends on the service, district, visit time and urgency. The final price is confirmed before the visit.', cta: 'Book on WhatsApp', note: 'Prices are indicative. Extra time, remote areas or urgent visits are confirmed in advance.' }
};

export const contactText = {
  RU: { badge: 'Контакты', h1: 'Записаться на визит медсестры', lead: 'Напишите в WhatsApp, позвоните или отправьте email. Мы уточним услугу, район, удобное время и подтвердим визит.', whatsapp: 'WhatsApp', call: 'Позвонить', email: 'Email', formH: 'Что написать в первом сообщении?', items: ['Какая услуга нужна', 'Город и район', 'Удобное время', 'Имя и номер для связи'] },
  KZ: { badge: 'Байланыс', h1: 'Медбике визитіне жазылу', lead: 'WhatsApp арқылы жазыңыз, қоңырау шалыңыз немесе email жіберіңіз. Біз қызметті, ауданды, ыңғайлы уақытты нақтылап, визитті растаймыз.', whatsapp: 'WhatsApp', call: 'Қоңырау шалу', email: 'Email', formH: 'Алғашқы хабарламада не жазу керек?', items: ['Қандай қызмет қажет', 'Қала және аудан', 'Ыңғайлы уақыт', 'Аты-жөні және байланыс нөмірі'] },
  EN: { badge: 'Contact', h1: 'Book a nurse visit', lead: 'Message us on WhatsApp, call or send an email. We will confirm the service, district, preferred time and visit details.', whatsapp: 'WhatsApp', call: 'Call', email: 'Email', formH: 'What to write in the first message?', items: ['Which service you need', 'City and district', 'Preferred time', 'Name and contact number'] }
};
